### ISSUE TITLE
Debugging that should'nt be there on the list of (Shared) Notebooks

### ISSUE THREAD

**Issue by Taluu** [evernote/evernote-cloud-sdk-php#13]
https://github.com/evernote/evernote-cloud-sdk-php/blob/master/src/Evernote/Client.php#L326

This kind of mess up every possible treatments. I think the error should be ignored, and logged if there is a Logger (How about asking for a PSR Logger, and use a NullLogger if there is none ?)

I'll try to make a PR on that if you like the idea.

**Comment by Laurent-Sarrazin** [comment]
A forgotten debug comment... Error handling is surely the biggest field of improvement of the SDK...
Ignoring this type of error is what I've done for the other ones so yeah I like the idea. +1 for the Logger too. I will happily accept your PR :)
Thanks Baptiste :D
