### ISSUE TITLE
Call to undefined method Evernote\Model\Notebook::isLinked()

### ISSUE THREAD

**Issue by jamesfairhurst** [evernote/evernote-cloud-sdk-php#20]
Line 1115 of Evernote/Client.php should be:

```if ($notebook->isLinkedNotebook() && !$notebook->isBusinessNotebook()) {```

Instead of:

```if ($notebook->isLinked() && !$notebook->isBusinessNotebook()) {```

Currently throwing a:

```Call to undefined method Evernote\Model\Notebook::isLinked()``` error

Would create a pull request myself however I've already forked the project for other minor changes.

**Comment by asamuylikrps** [comment]
Still not fixed, are you kidding?
