### ISSUE TITLE
is there a http api for evernote ? 

### ISSUE THREAD

**Issue by Ahmed-Badawy** [evernote/evernote-cloud-sdk-php#25]
i want to make add feature (save to evernote) in an app. like (Pocket & Instapaper).
could you help me to do this.

i know this might not be the place for this question. 
if this is the case could u plz direct me to the right place.

**Comment by akhaku** [comment]
Short answer: no. We use thrift for our API, and it looks like [the java version of our SDK uses HTTP](https://github.com/evernote/evernote-sdk-java/blob/master/src/main/java/com/evernote/thrift/transport/THttpClient.java), but it'll be fairly difficult to get it working without using one of our SDKs.

Also, the right place to ask this would be on [Stackoverflow](http://stackoverflow.com/questions/tagged/evernote).
