### ISSUE TITLE
A session had already been started - ignoring session_start()

### ISSUE THREAD

**Issue by ryandury** [evernote/evernote-cloud-sdk-php#28]
Trying to use this package within a Laravel app and i'm receiving the error:

ErrorException in OauthHandler.php line 53:
"A session had already been started - ignoring session_start()" 

I was able to comment this out and still have success with authenticating locally, but I will have to branch and modify this to work on production. 

Not sure if this package should manage session_start at all.  Open to suggestions :)

**Comment by garyns** [comment]
Hi. I'm new to Evernote's API, so excuse me if any of this is beginner-itis.

I'm getting the same error, only at line 76, using the sample code. I'm not starting a session anywhere and session.auto_start = 0

```
    [type] => 8
    [message] => A session had already been started - ignoring session_start()
    [file] => /test/server/ext/evernote/evernote-cloud-sdk-php/src/Evernote/Auth/OauthHandler.php
    [line] => 76
```

Updating line 76 to this fixed it.
```
if (session_status() == PHP_SESSION_NONE) {
  session_start();
}
```
I love the simplicity of this OAuth API. Looking at the code, my 2c worth would be to test for an active session always before trying to start one then it's really does not matter where it gets managed.

**Comment by akhaku** [comment]
Given that it needs a session to work, we still need the session_start() call IMO. Testing for an active session does seem like a good idea though.

**Comment by jult** [comment]
Just had to re-open this because I noticed this warning is often caused by changing the default of

```
[Session]
session.auto_start = 0
```
to
`session.auto_start = 1`

in php.ini

**Comment by shahzaib17** [comment]
session_reset();
this will do the trick
