### ISSUE TITLE
Tag a release

### ISSUE THREAD

**Issue by mpociot** [evernote/evernote-cloud-sdk-php#32]
Hi,

I'm using your PHP SDK in a [Laravel Notification channel](https://github.com/laravel-notification-channels/evernote) - in order to require a stable version, you should consider tagging a release of this SDK and updating it at packagist.

**Comment by akhaku** [comment]
I can tag a 1.0, but no one is actively working on this right now. It's one somebody's plate for when they get time...

**Comment by mpociot** [comment]
Thank you :)
