### ISSUE TITLE
Update "tijsverkoyen/css-to-inline-styles"

### ISSUE THREAD

**Issue by iksaku** [evernote/evernote-cloud-sdk-php#35]
Newer version of `tijsverkoyen/css-to-inline-styles` is available (2.2.0). It would be good to keep dependencies either updated or not locked to a specific version, instead, leave it as a "minimum required" version

**Comment by eugenecooper** [comment]
It's impossible to normally install this package for latest versions of Laravel because of that outdated dependency. Please update or unlock it.

**Comment by akhaku** [comment]
Thanks for #36, @eugenecooper. I'll tag a release now so y'all can pull down your fix.
