### ISSUE TITLE
Get notes from linked notebooks

### ISSUE THREAD

**Issue by bookin** [evernote/evernote-cloud-sdk-php#37]
How can I get/find/search notes from the linked/shared notebooks?
I have notebook guid, but method `findNotesWithSearch` don't want to get data from linked notebook.
I use a token authentication (without Auth)

**Comment by freakinhuge** [comment]
This should help you out a little. It took me a while to figure it out myself.

https://gist.github.com/freakinhuge/7dc96406e9aaeb3930b2cfc67248c7d2

**Comment by bookin** [comment]
@freakinhuge thanks for answer, I will see
