### ISSUE TITLE
How do I get access tokens?

### ISSUE THREAD

**Issue by BadTudou** [evernote/evernote-cloud-sdk-php#38]
I have applied for a temporary token and received user authorization.

But when I got the access token, I got:

`Oops, we encountered an error.`

I constructed an url to obtain the access token and access it through the browser, here is the url:

`https://sandbox.evernote.com/oauth?oauth_consumer_key=badtudou&oauth_token=badtudou.xxxxxxxxxxxxxxxxxxxxxxxxxxxx&oauth_verifier=D0361771C900B9530805BCFFABE999BD&oauth_nonce=d0b87b738748c02fe2c4c9e1bad55005&oauth_signature=p1y15nmRfHrv6OidmQ2dqGBthro=&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1501412888&oauth_version=1.0`

**xxxxxxxxxxxxx is my intention to write for privacy**

Or, can you give a sample of PHP from obtaining temporary tokens to obtaining access tokens?

Thank you very much!

**Comment by BadTudou** [comment]
any of the above parameters of url are obtained from the application of a temporary token.

The official example can not run, and when i run it to get the temporary token, I got 401

**Comment by lipkau** [comment]
@BadTudou : how did you solve this?
