### ISSUE TITLE
getNote method not working?

### ISSUE THREAD

**Issue by t1mmen** [evernote/evernote-cloud-sdk-php#9]
I'm having trouble getting ```Client::getNote``` to work using the current ```dev-master``` on PHP 5.5.10.

I have a valid OAuth token, and I'm listening to webhook events. Using the payload below, I'm attempting to query the note that was just updated. 

```php
$message = [
	'userId' => '287XXX',
	'guid' => '8ebd7180-XXXX',
	'notebookGuid' => 'd9de8217-XXXX',
	'reason' => 'update'
];
```

Using this info, I'm attempting to fetch the note using:

```php
$client = new \Evernote\Client($token, false); // token is valid, app is in production mode
$note = $client->getNote($message['guid']);
$notebook = $client->getNotebook($message['notebookGuid']);
```

In the above code, ```$note``` is empty, whereas ```$notebook``` returns the ```Evernote\Model\Notebook``` object, so I'm pretty sure everything is set up as it should.

Any pointers would be greatly appreciated

**Comment by Laurent-Sarrazin** [comment]
Hi Timm, 

What do you mean by "empty" ? No content ? Null ?
Are you sure the note has not been deleted ?
Is it a business note ? A note in an app notebook ? (It should work in these cases too but I'm trying to find what could be the cause of the issue).

Thanks !

**Comment by t1mmen** [comment]
Empty sting (''), note is not deleted, personal account, note is created from Evernote web app  in default notebook. I got the note id from a webhook event.

I can post note id when I am home again, if that helps. Thanks for looking into this for me!

**Comment by Laurent-Sarrazin** [comment]
hmm, well I guess I'll have to setup a webhook to check that as the getNote() works fine with a 'static' note guid...

**Comment by t1mmen** [comment]
Hold on, something weird is going on. I am using CakePHP on my end, and checking return values using [```debug()```](http://book.cakephp.org/2.0/en/development/debugging.html#basic-debugging), which works well with strings, arrays and objects... except the return from ```Client::getNote```, which just comes out as empty.

A ```var_dump``` or ```print_r```, on the other hand, does return the ```Evernote\Model\Note``` object. Perhaps this is related to the format of the ```content``` key? 

```php
// from above..
$client = new \Evernote\Client($token, false); // token is valid, app is in production mode
$note = $client->getNote($message['guid']);

print_r($note->content);

// outputs....
Evernote\Model\EnmlNoteContent Object
(
    [htmlConverter:protected] => 
    [content:protected] => <?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE en-note SYSTEM "http://xml.evernote.com/pub/enml2.dtd">
<en-note>
<div>Letâ€™s see whatÂ the webhook saysâ€¦.</div>
</en-note>

    [enmlConverter:protected] => 
)
```

Sorry about the misunderstanding. Perhaps this content formatting could be straight up HTML or Markdown? How would you recommend I parse this into HTML?

**Comment by Laurent-Sarrazin** [comment]
Pretty weird that the debug() method returns an empty string...
Anyway, you can try to use the toHtml() method on the content :
```php
$htmlContent = $note->content->toHtml();
```
This is mostly an "experimental" feature for now so let me know how it works for you.

**Comment by t1mmen** [comment]
Thanks, Laurent. Unfortunately, the ```toHtml``` didn't produce the desired result for me. It outputs:

```html
'<html><body>
<div>Letâ€™s see what the webhook says!</div>
<div><br></div>
</body></html>
```

.. but the encoding problem persists. Based on [this thread on Stackoverflow](http://stackoverflow.com/questions/2292004/getting-%C3%A2%E2%82%AC%E2%84%A2-instead-of-an-apostrophe-in-php), I managed to convert the encoding to UTF-8, making it usable for me.

Thank you for the assistance!

One last thing before closing this issue: Am I correct in assuming I need to do a seperate ```getNotebook``` call to get the name of the notebook? I'm not seeing it anywhere in the ```Evernote\Model\Note``` debug output.

**Comment by Laurent-Sarrazin** [comment]
Yep the conversion is pretty basic right now.
As for the notebook, yes you have to make another call. The notebook name is not included in the note.
